export function buildBridgeCommandHelp(): string {
  return [
    '<b>CodePilot Bridge Commands</b>',
    '',
    '/new [path] - Start new session',
    '/bind &lt;session_id&gt; - Bind to existing session',
    '/cwd /path - Change working directory',
    '/mode plan|code|ask - Change mode',
    '/status - Show current status',
    '/sessions - List recent sessions',
    '/stop - Stop current session',
    '/restart - Rebuild &amp; restart this bridge (npm install → build → restart)',
    '/git - Auto commit all changes',
    '/git help - Show /git usage',
    '/git draft - Generate commit draft (LLM)',
    '/git push - Push current branch',
    '/usage [今天|昨天|最近N天] - Show token usage summary',
    '/workflow start|status|resume|stop - Spec-Review 工作流',
    '/perm allow|allow_session|deny &lt;id&gt; - Respond to permission request',
    '1/2/3 - Quick permission reply (Feishu/QQ, single pending)',
    '/help - Show this help',
    '',
    '<b>Passthrough (透传)</b>',
    '//&lt;指令&gt; - 透传给 Claude（如 //review, //debug, //plan）',
    '//trellis:&lt;命令&gt; - Trellis 工作流（如 //trellis:start, //trellis:finish-work, //trellis:parallel）',
    '/codex:&lt;角色&gt; - 透传给 Codex（如 /codex:analyze, /codex:review）',
    '//help - Claude 透传命令完整清单',
    '/codex:help - Codex 透传命令完整清单',
  ].join('\n');
}
