export function buildBridgeCommandHelp(): string {
  return [
    '<b>CodePilot Bridge Commands</b>',
    '',
    '/new [path] - Start new session',
    '/bind &lt;session_id&gt; - Bind to existing session',
    '/cwd /path - Change working directory',
    '/mode plan|code|ask - Change mode',
    '/model - Codex 飞书模型卡：选择模型，再选强度和正常／Fast，点击应用',
    '/model &lt;model-id&gt; [effort] - 文字设置；/model default 跟随 Codex 默认',
    'Codex 配置仅在当前聊天生效，/new 和重启后保留；忙碌时请等待或先 /stop。Fast 用量更高。',
    '/status - Show current status',
    '/sessions - List recent sessions',
    '/stop - 取消当前任务及所有等待消息',
    '/retry [id] - 重投发送失败的回答（不重新调用模型）',
    '/git - Auto commit all changes',
    '/git help - Show /git usage',
    '/git draft - Generate commit draft (LLM)',
    '/git push - Push current branch',
    '/usage [今天|昨天|最近N天] - Show token usage summary',
    '/workflow spec-review|code-review|status|resume|stop - Workflow 工作流',
    '/perm allow|allow_session|deny &lt;id&gt; - Respond to permission request',
    '/answer &lt;id&gt; &lt;答案或JSON&gt; - 回答模型提问',
    '1/2/3 - Quick permission reply (Feishu/QQ, single pending)',
    '/help - Show this help',
    '',
    '<b>Passthrough (透传)</b>',
    '//&lt;指令&gt; - 透传给 Claude（如 //review, //debug, //plan）',
    '//trellis:&lt;命令&gt; - Trellis 工作流（如 //trellis:start, //trellis:finish-work, //trellis:parallel）',
    '//fusion:&lt;命令&gt; - Fusion 增强（如 //fusion:brainstorm-plus, //fusion:checkpoint）',
    '/codex:&lt;角色&gt; - 透传给 Codex（如 /codex:analyze, /codex:review）',
    '//help - Claude 透传命令完整清单',
    '/codex:help - Codex 透传命令完整清单',
  ].join('\n');
}
